"""replay.py – re-apply a snapshot's environment state as a shell-sourceable script.

Given a snapshot dict the module renders a POSIX shell script that, when
sourced, activates the recorded Python virtualenv (if present), sets the
captured environment variables, and optionally switches to the recorded
Node version via nvm.
"""
from __future__ import annotations

import json
import os
import shlex
from pathlib import Path
from typing import Optional


def _load_snapshot(path: Path) -> dict:
    with path.open() as fh:
        return json.load(fh)


def build_replay_script(snapshot: dict, *, include_node: bool = True) -> str:
    """Return a POSIX shell script string that replays *snapshot*."""
    lines: list[str] = ["#!/usr/bin/env sh", "# generated by stacksnap replay", ""]

    label = snapshot.get("label", "unknown")
    lines.append(f"echo 'Replaying snapshot: {shlex.quote(label)}'")
    lines.append("")

    # --- environment variables ---
    env_vars: dict = snapshot.get("env_vars") or {}
    if env_vars:
        lines.append("# environment variables")
        for key, value in env_vars.items():
            safe_val = shlex.quote(str(value))
            lines.append(f"export {key}={safe_val}")
        lines.append("")

    # --- python virtualenv ---
    python_info: dict = snapshot.get("python") or {}
    venv = python_info.get("virtualenv")
    if venv:
        activate = os.path.join(venv, "bin", "activate")
        lines.append("# python virtualenv")
        lines.append(f"if [ -f {shlex.quote(activate)} ]; then")
        lines.append(f"  . {shlex.quote(activate)}")
        lines.append("else")
        lines.append(f"  echo 'WARNING: virtualenv not found at {venv}'")
        lines.append("fi")
        lines.append("")

    # --- node version via nvm ---
    if include_node:
        node_info: dict = snapshot.get("node") or {}
        node_version = node_info.get("version")
        if node_version:
            lines.append("# node version")
            lines.append("if command -v nvm > /dev/null 2>&1; then")
            lines.append(f"  nvm use {shlex.quote(node_version)} || true")
            lines.append("fi")
            lines.append("")

    lines.append("echo 'Replay complete.'")
    return "\n".join(lines) + "\n"


def replay_snapshot(
    snapshot_path: Path,
    output_path: Optional[Path] = None,
    *,
    include_node: bool = True,
) -> str:
    """Load *snapshot_path* and write (or return) a replay shell script.

    If *output_path* is given the script is written there and the path string
    is returned; otherwise the script text is returned directly.
    """
    snapshot = _load_snapshot(snapshot_path)
    script = build_replay_script(snapshot, include_node=include_node)
    if output_path is not None:
        output_path.write_text(script)
        output_path.chmod(0o755)
        return str(output_path)
    return script
